#server:
#  port: 8005
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/EmployeeDB
#    password: password
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    generate:
#      ddl: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  application:
#    name: employee-service
#  batch:
#    initialize-schema: ALWAYS
#    job :
#      enabled: true
#
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${eureka_url:http://localhost:8761/eureka}
#
